### ISSUE TITLE
Integrate error message processing from webpack

### ISSUE THREAD

**Issue by sokra** [webpack-contrib/schema-utils#18]
see https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsValidationError.js

This module makes errors from ava look more nice:

* It groups multiple messages from `oneOf` etc. into one message
* It displays a short readable version of the schema
* It uses better messages
* It displays `description` from schema next to each error

For examples see https://github.com/webpack/webpack/blob/master/test/Validation.test.js#L35-L46

**Comment by sokra** [comment]
see also webpack/webpack#5892

**Comment by shellscape** [comment]
I believe this issue is now outdated.
