### ISSUE TITLE
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0

### ISSUE THREAD

**Issue by nkfly** [webpack-contrib/schema-utils#24]
The release you had yesterday causes our error when running "npm ls".

The error message is:
npm ERR! peer dep missing: ajv@^6.0.0, required by ajv-keywords@3.1.0

So, you should make the version to be 1.0.0 ?
Thanks.

**Comment by Ankiitt** [comment]
+1

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/schema-utils/issues/23#issuecomment-365392978
