### ISSUE TITLE
ValidationError: UglifyJs Plugin Invalid Options

### ISSUE THREAD

**Issue by sazr** [webpack-contrib/schema-utils#27]
So heres my issue, I run the command `npm run production` and the following error is output:

> - @ production C:\Users\foo
> - node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=producti
> on node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
> 
> C:\Users\foo\node_modules\schema-utils\dist\validateOptions.js:44
>     throw new _ValidationError2.default(ajv.errors, name);
>     ^
> 
> ValidationError: UglifyJs Plugin Invalid Options
> 
> options should be object

If I run my command `npm run watch` everything is fine. Any idea what the heck is wrong?

In attempting to fix this I have updated the following packages to the latest versions but the error still occurs; uglify-js, schema-utils, ajv.

* Operating System: Windows 10
* Node Version: 6.11.3
* NPM Version: 3.10.10
* webpack Version:
* schema-utils Version: 0.4.5

This issue is for a:
- [x] **bug**

##### CLI Command

```    "watch": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",   

    "production": "node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
```

**Comment by evilebottnawi** [comment]
@sazr please read error and fix it, looks like you don't use `object` for uglify plugin. Please add example how you use uglify plugin and reopen issue.
