### ISSUE TITLE
custom keyword definition is invalid error

### ISSUE THREAD

**Issue by ksato9700** [webpack-contrib/schema-utils#38]
I ran `yarn install` followed by `yarn run test` and got the following error.

```
    custom keyword definition is invalid: data/errors should be boolean
```

### Details

I believe this is due to the incompatibility of ajv-errors that requires ajv@^5.0.0.

### Error (Logs|Stacks)
https://gist.github.com/ksato9700/86071b00242cb39c537dc916e030400c

### Reproduction (Code)

```bash
$ git clone https://github.com/webpack-contrib/schema-utils.git
$ cd schema-utils/
$ yarn install
$ yarn run test
```

### Environment

|OS|node|npm/yarn|package|
|:-:|:--:|:-:|:------:|
|macOS 10.14.2|v10.15.1|yarn 1.13.0|6ca2322|

**Comment by evilebottnawi** [comment]
Already fixed in deps
